field_map_dict = {"Date": "Date",
                  "Total Enabled Membership": "Total_Enabled_Membership",
                  "Enabled Full Members": "Enabled_Full_Members",
                  "Enabled Guests": "Enabled_Guests",
                  "Daily active members": "Daily_active_members",
                  "Daily members posting messages": "Daily_members_posting_messages",
                  "Weekly active members": "Weekly_active_members",
                  "Weekly members posting messages": "Weekly_members_posting_messages",
                  "Messages in public channels": "Messages_in_public_channels",
                  "Messages in private channels": "Messages_in_private_channels",
                  "Messages in shared channels": "Messages_in_shared_channels",
                  "Messages in DMs": "Messages_in_DMs",
                  "Percent of messages, public channels": "Percent_of_messages_public_channels",
                  "Percent of messages, private channels": "Percent_of_messages_private_channels",
                  "Percent of messages, DMs": "Percent_of_messages_DMs",
                  "Percent of views, public channels": "Percent_of_views_public_channels",
                  "Percent of views, private channels": "Percent_of_views_private_channels",
                  "Percent of views, DMs": "Percent_of_views_DMs",
                  "Total Full Members": "Total_Full_Members",
                  "Total Guests": "Total_Guests",
                  "Total Claimed Full Members": "Total_Claimed_Full_Members",
                  "Total Claimed Guests": "Total_Claimed_Guests",
                  "Total Members": "Total_Members",
                  "Total Claimed Members": "Total_Claimed_Members",
                  "Files uploaded": "Files_uploaded",
                  "Messages posted by members": "Messages_posted_by_members",
                  "Name": "Name",
                  "Public channels, single-workspace": "Public_channels_single_workspace",
                  "Messages posted": "Messages_posted",
                  "Messages posted by apps": "Messages_posted_by_apps"}

attr_field_map_dict = {"date": "Date",
                       "total_enabled_membership": "Total_Enabled_Membership",
                       "enabled_full_members": "Enabled_Full_Members",
                       "enabled_guests": "Enabled_Guests",
                       "daily_active_members": "Daily_active_members",
                       "daily_members_posting_messages": "Daily_members_posting_messages",
                       "weekly_active_members": "Weekly_active_members",
                       "weekly_members_posting_messages": "Weekly_members_posting_messages",
                       "messages_in_public_channels": "Messages_in_public_channels",
                       "messages_in_private_channels": "Messages_in_private_channels",
                       "messages_in_shared_channels": "Messages_in_shared_channels",
                       "messages_in_dms": "Messages_in_DMs",
                       "percent_of_messages_public_channels": "Percent_of_messages_public_channels",
                       "percent_of_messages_private_channels": "Percent_of_messages_private_channels",
                       "percent_of_messages_dms": "Percent_of_messages_DMs",
                       "percent_of_views_public_channels": "Percent_of_views_public_channels",
                       "percent_of_views_private_channels": "Percent_of_views_private_channels",
                       "percent_of_views_dms": "Percent_of_views_DMs",
                       "total_full_members": "Total_Full_Members",
                       "total_guests": "Total_Guests",
                       "total_claimed_full_members": "Total_Claimed_Full_Members",
                       "total_claimed_guests": "Total_Claimed_Guests",
                       "total_members": "Total_Members",
                       "total_claimed_members": "Total_Claimed_Members",
                       "files_uploaded": "Files_uploaded",
                       "messages_posted_by_members": "Messages_posted_by_members",
                       "name": "Name",
                       "public_channels_single_workspace": "Public_channels_single_workspace",
                       "messages_posted": "Messages_posted",
                       "messages_posted_by_apps": "Messages_posted_by_apps"}
